import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Sandbox } from './sandbox'

const Home: NextPage = () => {
  return (
    <div className="flex items-center justify-center h-screen w-screen bg-orange-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sandbox />
    </div>
  )
}

export default Home
